---
- name: AS3 http setup 
  hosts: "{{ target }}"
  gather_facts: false
  vars:
    AS3Version: "3.22.1-1"
    provider:
      server: "{{ inventory_hostname }}"
      server_port: "{{ server_port }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"

  tasks:

  - name: Manage AS3 externsion version {{ AS3Version }}
    bigip_lx_package:
      provider: "{{ provider }}"
      package: "files/f5-appsvcs-{{ AS3Version }}.noarch.rpm"
      state: "{{ state }}" 
    delegate_to: localhost


...    
